### ISSUE TITLE
Cannot read property 'randomBytes' of undefined

### ISSUE THREAD

**Issue by gzcheng** [drophive/react-native-pkce-challenge#6]
getting "Cannot read property 'randomBytes' of undefined"

I think you should mention that this library requires [react-native-randombytes](https://github.com/mvayngrib/react-native-randombytes) to work.
At least this is the case for me using RN 0.59

thanks

**Comment by dcangulo** [comment]
@gzcheng Please reopen if the issue still persists on the new version. 👍
